<a href="https://colab.research.google.com/github/joaocarvoli/MachineLearning-course/blob/main/05_problem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problem 05:
## _In this exercise, the 05, We'll build the functions about classification and regression metrics. Building each one and  just using a piece of scikit learn._

In [2]:
import numpy
import pandas
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

## 0. Imports to test:

### To classification:

In [3]:
# I'M IMPORTING THIS DATASET JUST TO TEST AND COMPARE THE REGRESSION METRICS AND TO TEST CLASSIFICATION METRICS
white_wine = pandas.read_csv('/content/drive/MyDrive/data-sets/winequality/winequality-white.csv', nrows = 50, delimiter=';')
X = white_wine.iloc[:,:11]
y = white_wine.iloc[:,11:]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

# Just training the K-neighbors-nearest and K-neighbors-regressor without parameters adjust, just to test:

# KNN - Classification

model_class = KNeighborsClassifier(n_neighbors = 5, weights = 'distance')
model_class.fit(X_train, y_train.values.ravel())

y_pred_classification = model_class.predict(X_test)
y_test = numpy.array(y_test['quality'].values)
print(y_pred_classification, type(y_pred_classification))
print(y_test, type(y_test))

[6 5 6 6 8 6 6 5 6 6 5 6 6 6 6] <class 'numpy.ndarray'>
[7 5 6 7 8 6 6 6 6 5 5 6 6 6 6] <class 'numpy.ndarray'>


### To regression

In [4]:
model_regressor = KNeighborsRegressor(n_neighbors = 5, weights = 'distance')
model_regressor.fit(X_train, y_train.values.ravel())

y_pred_regressor = model_regressor.predict(X_test)
print(y_pred_regressor, type(y_pred_regressor), y_pred_regressor.shape)
print(y_test, type(y_test), y_test.shape)

[5.59996293 5.         5.77120026 5.61408753 8.         6.
 5.60946758 4.86727729 6.17614042 6.14931754 6.42046739 5.26298858
 5.82553765 6.         5.26298858] <class 'numpy.ndarray'> (15,)
[7 5 6 7 8 6 6 6 6 5 5 6 6 6 6] <class 'numpy.ndarray'> (15,)


## 1. Classification:

In [7]:
y_true = numpy.array(['dog', 'dog', 'dog', 'dog', 'dog', 'dog',
    'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat', 'cat',      
     'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit',
     'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit'])

y_pred = numpy.array(['dog', 'dog', 'dog', 'rabbit', 'cat', 'cat',
     'cat', 'cat', 'cat', 'cat', 'cat', 'dog', 'dog', 'dog', 
     'dog', 'dog', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit',
     'rabbit', 'rabbit', 'rabbit', 'rabbit', 'rabbit'])

### Accuracy:

In [ ]:
def accuracy(y_true:numpy.array, y_pred:numpy.array): 
    equals = numpy.count_nonzero(y_true == y_pred, axis = 0)
    accuracy = equals / numpy.count_nonzero(y_pred, axis = 0)
    return accuracy

In [ ]:
accuracy(y_true, y_pred)

0.7037037037037037

### _Accuracy: Using Sckit Learn_


In [ ]:
metrics.accuracy_score(y_true, y_pred)

0.7037037037037037

### Precision:

In [ ]:
def precision(y_true: numpy.array, y_pred:numpy.array):
    classes_precision = []
    matrix = metrics.confusion_matrix(y_true, y_pred)
    classes = matrix.shape[1]

    for i in range(1, classes + 1):
        true_positive = matrix[i-1:i,i-1:i]
        false_positive = numpy.sum(matrix[:,i-1:i])  - matrix[i-1:i,i-1:i]

        precision = numpy.array(true_positive / (true_positive + false_positive))
        # If a NaN exists...
        precision = numpy.nan_to_num(precision)

        classes_precision.append(precision)

    # Calculating Precision Weighted of each class and doing the mean
    unique, weights = numpy.unique(y_true, return_counts=True)
    del unique
    weights = numpy.array(weights)   
    weighted_mean = numpy.repeat(classes_precision, weights).mean()
    weighted_mean = float(weighted_mean)
    # Return the weighted mean of precisions
    return weighted_mean

In [ ]:
precision(y_true, y_pred)

0.7363315696649031

### _Precision: Using Sckit Learn_

In [ ]:
metrics.precision_score(y_true, y_pred, average= 'weighted')

0.736331569664903

### Recall:

In [13]:
def recall(y_true: numpy.array, y_pred:numpy.array):
    classes_recall = []
    matrix = metrics.confusion_matrix(y_true, y_pred)
    classes = matrix.shape[1]

    for i in range(1, classes + 1):
        true_positive = matrix[i-1:i,i-1:i]
        false_positive = numpy.sum(matrix[i-1:i,:])  - matrix[i-1:i,i-1:i]

        recall = numpy.array(true_positive / (true_positive + false_positive))
        # If a NaN exists...
        recall = numpy.nan_to_num(recall)

        classes_recall.append(recall)

    # Calculating Precision Weighted of each class and doing the mean
    unique, weights = numpy.unique(y_true, return_counts=True)
    del unique
    weights = numpy.array(weights)   
    recall_mean = numpy.repeat(classes_recall, weights).mean()
    recall_mean = float(recall_mean)
    # Return the weighted mean of precisions
    return recall_mean

In [14]:
recall(y_true, y_pred)

0.7037037037037037

### _Recall: Using Sckit Learn_

In [ ]:
metrics.recall_score(y_true, y_pred, average= 'weighted')

0.7037037037037037

### $F1$ - Measure:

In [ ]:
def f1_score(y_true: numpy.array, y_pred:numpy.array, recall, precision):
    f1 = (2*precision_res*recall_res) / (precision_res + recall_res)
    return f1

In [ ]:
recall_res = recall(y_true, y_pred)
precision_res = precision(y_true, y_pred)

f1_score(y_true, y_pred, recall = recall_res, precision = precision_res)

0.7196480007257717

### _$F1 - Score$: Using Sckit Learn_

In [ ]:
metrics.f1_score(y_true, y_pred, average  = 'weighted')

0.7164726631393298

#### _The above results are slightly different due to rounding_



------



## Testing in a bigger problem:

### 1.1 Accuracy:

In [ ]:
accuracy(y_true=y_test, y_pred=y_pred_classification)

0.7333333333333333

In [ ]:
metrics.accuracy_score(y_true=y_test, y_pred=y_pred_classification)

0.7333333333333333

### 1.2 Recall:

In [ ]:
recall(y_true=y_test, y_pred=y_pred_classification)

0.7333333333333333

In [ ]:
metrics.recall_score(y_true=y_test, y_pred=y_pred_classification, average= 'weighted')

0.7333333333333333

### 1.3 Precision:


In [ ]:
precision(y_true=y_test, y_pred=y_pred_classification)

0.6363636363636365

In [ ]:
metrics.precision_score(y_true=y_test, y_pred=y_pred_classification, average= 'weighted')

0.6363636363636365

### 1.4 $F1 - Score:$

In [ ]:
recall_res = recall(y_test, y_pred_classification)
precision_res = precision(y_test, y_pred_classification)

f1_score(y_true, y_pred, recall = recall_res, precision = precision_res)

0.68141592920354

In [ ]:
metrics.f1_score(y_true=y_test, y_pred=y_pred_classification, average= 'weighted')

0.6799999999999999

#### _The above results are slightly different due to rounding_



------



## 2. Regression: 

#### MEA: 

In [ ]:
def mea(y_true: numpy.array, y_pred:numpy.array):
    mea = (1/y_pred.shape[0])*(numpy.sum(abs(y_pred - y_true)))
    return mea

In [ ]:
mea(y_true=y_test, y_pred=y_pred_classification)

0.26666666666666666

### _MEA: Using Sckit Learn_

In [ ]:
metrics.mean_absolute_error(y_true=y_test, y_pred=y_pred_classification)

0.26666666666666666

### RMSE & MSE

In [ ]:
def mse(y_true: numpy.array, y_pred:numpy.array):
    mse = (1/y_pred.shape[0])*(numpy.sum((y_pred - y_true)**2))
    return mse

In [ ]:
print('MSE: ', mse(y_true=y_test, y_pred=y_pred_classification))
print('RMSE:', mse(y_true=y_test, y_pred=y_pred_classification)*0.5)

MSE:  0.26666666666666666
RMSE: 0.13333333333333333


### _RMSE & MSE: Using Sckit Learn_

In [ ]:
print(metrics.mean_squared_error(y_true=y_test, y_pred=y_pred_classification))
print(metrics.mean_squared_error(y_true=y_test, y_pred=y_pred_classification)*0.5)

0.26666666666666666
0.13333333333333333


### _The application of these functions has already done in_ [`4.2 Exercise`](https://nbviewer.jupyter.org/github/joaocarvoli/MachineLearning-course/blob/main/Exercises/04.2-problem.ipynb), _see there!_